name: Update Quote

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 9 * * *'

jobs:
  update-readme:
    name: Update Quote in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch and inject quote
        run: |
          QUOTE_DATA=$(curl -s "https://api.irwanx.my.id/api/quotes/random")
          QUOTE_TEXT=$(echo "$QUOTE_DATA" | jq -r '.data.quotes')
          QUOTE_AUTHOR=$(echo "$QUOTE_DATA" | jq -r '.data.author')

          QUOTE="> \"${QUOTE_TEXT}\" - *${QUOTE_AUTHOR}*"

          START="<!-- START_QUOTE -->"
          END="<!-- END_QUOTE -->"

          awk -v start="$START" -v end="$END" -v quote="$QUOTE" '
            $0 ~ start { print; print quote; skip=1; next }
            $0 ~ end { skip=0 }
            !skip
          ' README.md > temp.md && mv temp.md README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Update daily quote"
          commit_user_name: "irwanx"
          commit_user_email: "irwan080304@gmail.com"
          commit_author: "irwanx <irwan080304@gmail.com>"
