name: Waka Readme

on:
  # for push event
  push:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # required if committing to profile README
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required

          # Meta
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: irwanx/irwanx

          # Content settings
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          CODE_LANG: rust
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML

          # Commit settings
          COMMIT_MESSAGE: "Automated Coding Activity Update :bulb:"
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: irwanx
          AUTHOR_EMAIL: irwan080304@gmail.com
